---
# run provision and build tasks on all hosts (various groups specified below)

# hosts: all handles tasks for all hosts and gets variables from all.yml
- name: Build environment for running bactopia
  hosts: all
  become: true
  vars_files:
      - "{{ inventory_dir }}/group_vars/all.yml"

  pre_tasks:
      - name: Get current server users
        ansible.builtin.getent:
            database: passwd
            fail_key: true

      - name: "Ensure bactopia service added to user: {{ bactopia_user }}"
        ansible.builtin.user:
            name: "{{ bactopia_user }}"
            shell: /sbin/nologin
            comment: "bactopia system user"
            state: present
        with_items: "{{ bactopia_user }}"
        when: bactopia_user not in ansible_facts.getent_passwd

      - name: Install python3
        ansible.builtin.yum:
            name: python3
            state: present

      - name: Install git
        ansible.builtin.yum:
            name: git
            state: present

      - name: Install docker
        ansible.builtin.yum:
            name: docker
            state: present

      - name: "Add user to docker group: {{ bactopia_user }}"
        ansible.builtin.user:
            name: "{{ bactopia_user }}"
            append: true
            groups: docker

      - name: Enable and start docker service
        ansible.builtin.systemd:
            daemon_reload: true
            name: docker
            enabled: true
            state: started

      - name: Download Anaconda3
        ansible.builtin.get_url:
            url: https://repo.anaconda.com/archive/Anaconda3-2023.07-2-Linux-x86_64.sh
            dest: /tmp/install-anaconda3.sh
            checksum: sha256:589fb34fe73bc303379abbceba50f3131254e85ce4e7cd819ba4276ba29cad16
            mode: "0550"

      - name: Create conda folder
        become: true
        ansible.builtin.file:
            path: /opt/anaconda3
            state: directory
            owner: root
            mode: "0755"
            recurse: true

      - name: Install conda
        ansible.builtin.command: |
            /tmp/install-anaconda3.sh -b -u -p /opt/anaconda3
        changed_when: false

      - name: Remove anaconda installer
        ansible.builtin.file:
            state: absent
            path: /tmp/install-anaconda3.sh

      - name: Add anaconda bin to path on login
        ansible.builtin.lineinfile:
            path: /etc/profile
            line: "export PATH=/opt/anaconda3/bin:$PATH"
            create: true
            mode: "0644"

      - name: Initialize anaconda on login
        become: true
        ansible.builtin.file:
            src: /opt/anaconda3/etc/profile.d/conda.sh
            dest: /etc/profile.d/conda.sh
            state: link

      - name: Allow all to read conda folder
        become: true
        ansible.builtin.file:
            path: /opt/anaconda3
            mode: +r
            recurse: true

      - name: Allow execution for conda binaries
        become: true
        ansible.builtin.file:
            path: /opt/anaconda3/bin
            mode: +x
            recurse: true

      - name: Instantiate bactopia environment
        ansible.builtin.command: |
            bash -l -c 'conda create -n bactopia -c conda-forge -c bioconda bactopia -y'
        changed_when: false

      - name: Activate bactopia environment on login
        ansible.builtin.lineinfile:
            path: /etc/profile
            line: "conda activate bactopia"

      - name: Copy bactopia run script to the VM
        ansible.builtin.copy:
            src: files/run-bactopia-local.sh
            dest: /home/vagrant/run-bactopia-local.sh
            mode: "755"
